
//Inserir----------------------------
let request = require("request");
let token = '6:4dacdb8e47193e8cbbabe508c3c59b4547e463817b1d9b9a1d20ab4812fe1a62';
let options = { method: 'POST',
  url: 'https://HOST/webservice/v1/voip_sippeers',
  headers:
   {
     'Content-Type': 'application/json',
     Authorization: 'Basic ' + new Buffer.from(token).toString('base64')
   },
  body:{
    'faxdetect': '',
    't38pt_usertpsource': '',
    'tarifa': '',
    'id_contrato': '',
    'id_integracao': '',
    'summit_bid_type': 'TERMINAL',
    'trunk_summit': '',
    'descricao': '',
    'accountcode': '',
    'callerid': '',
    'name': '0',
    'tipo_linha_sip': 'N',
    'secret': '',
    'senha_ata': '',
    'mailbox': '',
    'comments_summit': '',
    'informacao_portabilidade_sip': '',
    'id_perfis_voip': '',
    'ativo': 'S',
    'tysa_line_type': '0',
    'tysa_line_user_type': '0',
    'tysa_line_status': '2',
    'tysa_line_call_limit': '',
    'tysa_line_ip_add': '',
    'tysa_line_function': '0',
    'particao_assinante_summit': '',
    'categoria_summit': '',
    'plano_summit': '',
    'data_ativacao_summit': '',
    'vencimento_summit': '',
    'centro_custo_summit': '',
    'limite_chamadas_summit': '0',
    'licenca_summit': '',
    'terminal_summit': '',
    'credential_summit': '',
    'context': 'LinhaConvencional',
    'callgroup': '',
    'pickupgroup': '',
    'allowtransfer': 'yes',
    'disallow': 'all',
    'allow': 'ulaw',
    'videosupport': 'no',
    'textsupport': 'no',
    'gravacao_chamada': 'N',
    'call-limit': '1',
    'rtptimeout': '120',
    'rtpholdtimeout': '300',
    'rtpkeepalive': '',
    'qualify': '',
    'qualifyfreq': '',
    'timert1': '',
    'timerb': '',
    'session-timers': '',
    'session-refresher': '',
    'session-minse': '',
    'session-expires': '',
    'subscribemwi': '',
    'vmexten': '',
    'hasvoicemail': '',
    'mohinterpret': '',
    'mohsuggest': '',
    'allowsubscribe': '',
    'allowoverlap': '',
    'autoframing': '',
    'cid_number': '',
    'callingpres': '',
    'fullname': '',
    'numero': '',
    'fromdomain': '',
    'fromuser': '',
    'defaultuser': '',
    'defaultip': '',
    'trunkname': '',
    'buggymwi': 'yes',
    'dynamic': '',
    'setvar': '',
    'outboundproxy': '',
    'callcounter': '',
    'useclientcode': 'yes',
    'usereqphone': 'no',
    'ignoresdpversion': '',
    'trustrpid': '',
    'promiscredir': 'no',
    'sendrpid': '',
    'progressinband': '',
    'constantssrc': '',
    'maxcallbitrate': '',
    'busylevel': '',
    'callbackextension': '',
    'regexten': '',
    'amaflags': '',
    'auth': '',
    'parkinglot': '',
    'md5secret': '',
    'remotesecret': '',
    'regserver': '',
    'lastms': '',
    'directmedia': '',
    'path': '',
    'dtmfmode': 'rfc2833',
    'language': 'pt_BR',
    'type': 'friend',
    'rfc2833compensate': 'yes',
    'transport': 'udp',
    'insecure': '',
    'permit': '',
    'deny': '',
    'status_ramal': 'A',
    'vsc_id_batch': '',
    'vsc_batch': '',
    'vsc_allowcollectcalls': 'true',
    'vsc_dontuseccforauth': 'true',
    'ddi_vsc': '',
    'use_area_code': 'N',
    'ddd_vsc': '',
    'vsc_idd_prefix': '',
    'vsc_ndd_prefix': '',
    'vsc_inboundcallslimit': '1',
    'vsc_outboundcallslimit': '1',
    'user_code': '',
    'billing': 'C',
    'credit_limit': '',
    'recharge_settings': 'N',
    'dia_recarga_padrao': '',
    'saperx_plano': '',
    'saperx_plano_inter': '',
    'dia_fechamento': '1',
    'saperx_plano_desc': '',
    'saperx_tipo': '0',
    'sapex_plano_tipo': 'scm',
    'rota_personalizada': '',
    'saperx_bina': '0',
    'saperx_lc': '0',
    'saperx_ldn': '0',
    'saperx_vc1': '0',
    'saperx_vc2': '0',
    'saperx_vc3': '0',
    'saperx_ativo': '1',
    'plano_zeus': '',
    'grupo_plano_zeus': '',
    'data_ativacao_zeus': '',
    'vencimento_zeus': '',
    'limite_creditos_zeus': '100',
    'tech_prefix_zeus': '',
    'bloquear_ligacoes_vc1_zeus': 'S',
    'bloquear_ligacoes_cobrar_zeus': 'S',
    'bloquear_ligacoes_ldn_zeus': 'S',
    'bloquear_ligacoes_ldi_zeus': 'S',
    'nao_perturbe_zeus': '1',
    'fullcontact': '',
    'ipaddr': '',
    'port': '',
    'regseconds': '',
    'useragent': '',
    'nat': 'no',
    'host': 'dynamic',
    'contactpermit': '',
    'contactdeny': '',
    'sippulse_dominio': '',
    'profile': '',
    'id_revenda_sip_pulse': '',
    'sippulse_rateplanid': '',
    'ddd': '',
    'ddi': '',
    'sippulse_city_code': '',
    'sippulse_local_area': '',
    'sippulse_lowCreditNotification': 'true',
    'sippulse_activeIncomingCalls': 'true',
    'sippulse_activeOutgoingCalls': 'true',
    'sippulse_activatedailystatistics': 'true',
    'sippulse_callsOnlyByIp': 'true',
    'sippulse_daily_quota': 'true',
    'sippulse_daily_quota_tipo': 'M',
    'sippulse_dailyQuotaConsumed': '0',
    'sippulse_dailyQuotaLimit': '0',
    'plano_magnus': ''
  },
  json: true
 };
request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});

//Deletar----------------------------
let request = require("request");
let token = '6:4dacdb8e47193e8cbbabe508c3c59b4547e463817b1d9b9a1d20ab4812fe1a62';
let options = { method: 'DELETE',
  url: 'https://HOST/webservice/v1/voip_sippeers/Id_a_deletar',
  headers:
   {
     'Content-Type': 'application/json',
     Authorization: 'Basic ' + new Buffer.from(token).toString('base64')
   }
 };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});

//Editar----------------------------
let request = require("request");
let token = '6:4dacdb8e47193e8cbbabe508c3c59b4547e463817b1d9b9a1d20ab4812fe1a62';
let options = { method: 'PUT',
  url: 'https://HOST/webservice/v1/voip_sippeers/Id_a_editar',
  headers:
   {
     'Content-Type': 'application/json',
     Authorization: 'Basic ' + new Buffer.from(token).toString('base64')
   },
  body:
   {
    "faxdetect": "",
    "t38pt_usertpsource": "",
    "tarifa": "",
    "id_contrato": "",
    "id_integracao": "",
    "summit_bid_type": "TERMINAL",
    "trunk_summit": "",
    "descricao": "",
    "accountcode": "",
    "callerid": "",
    "name": "0",
    "tipo_linha_sip": "N",
    "secret": "",
    "senha_ata": "",
    "mailbox": "",
    "comments_summit": "",
    "informacao_portabilidade_sip": "",
    "id_perfis_voip": "",
    "ativo": "S",
    "tysa_line_type": "0",
    "tysa_line_user_type": "0",
    "tysa_line_status": "2",
    "tysa_line_call_limit": "",
    "tysa_line_ip_add": "",
    "tysa_line_function": "0",
    "particao_assinante_summit": "",
    "categoria_summit": "",
    "plano_summit": "",
    "data_ativacao_summit": "",
    "vencimento_summit": "",
    "centro_custo_summit": "",
    "limite_chamadas_summit": "0",
    "licenca_summit": "",
    "terminal_summit": "",
    "credential_summit": "",
    "context": "LinhaConvencional",
    "callgroup": "",
    "pickupgroup": "",
    "allowtransfer": "yes",
    "disallow": "all",
    "allow": "ulaw",
    "videosupport": "no",
    "textsupport": "no",
    "gravacao_chamada": "N",
    "call-limit": "1",
    "rtptimeout": "120",
    "rtpholdtimeout": "300",
    "rtpkeepalive": "",
    "qualify": "",
    "qualifyfreq": "",
    "timert1": "",
    "timerb": "",
    "session-timers": "",
    "session-refresher": "",
    "session-minse": "",
    "session-expires": "",
    "subscribemwi": "",
    "vmexten": "",
    "hasvoicemail": "",
    "mohinterpret": "",
    "mohsuggest": "",
    "allowsubscribe": "",
    "allowoverlap": "",
    "autoframing": "",
    "cid_number": "",
    "callingpres": "",
    "fullname": "",
    "numero": "",
    "fromdomain": "",
    "fromuser": "",
    "defaultuser": "",
    "defaultip": "",
    "trunkname": "",
    "buggymwi": "yes",
    "dynamic": "",
    "setvar": "",
    "outboundproxy": "",
    "callcounter": "",
    "useclientcode": "yes",
    "usereqphone": "no",
    "ignoresdpversion": "",
    "trustrpid": "",
    "promiscredir": "no",
    "sendrpid": "",
    "progressinband": "",
    "constantssrc": "",
    "maxcallbitrate": "",
    "busylevel": "",
    "callbackextension": "",
    "regexten": "",
    "amaflags": "",
    "auth": "",
    "parkinglot": "",
    "md5secret": "",
    "remotesecret": "",
    "regserver": "",
    "lastms": "",
    "directmedia": "",
    "path": "",
    "dtmfmode": "rfc2833",
    "language": "pt_BR",
    "type": "friend",
    "rfc2833compensate": "yes",
    "transport": "udp",
    "insecure": "",
    "permit": "",
    "deny": "",
    "status_ramal": "A",
    "vsc_id_batch": "",
    "vsc_batch": "",
    "vsc_allowcollectcalls": "true",
    "vsc_dontuseccforauth": "true",
    "ddi_vsc": "",
    "use_area_code": "N",
    "ddd_vsc": "",
    "vsc_idd_prefix": "",
    "vsc_ndd_prefix": "",
    "vsc_inboundcallslimit": "1",
    "vsc_outboundcallslimit": "1",
    "user_code": "",
    "billing": "C",
    "credit_limit": "",
    "recharge_settings": "N",
    "dia_recarga_padrao": "",
    "saperx_plano": "",
    "saperx_plano_inter": "",
    "dia_fechamento": "1",
    "saperx_plano_desc": "",
    "saperx_tipo": "0",
    "sapex_plano_tipo": "scm",
    "rota_personalizada": "",
    "saperx_bina": "0",
    "saperx_lc": "0",
    "saperx_ldn": "0",
    "saperx_vc1": "0",
    "saperx_vc2": "0",
    "saperx_vc3": "0",
    "saperx_ativo": "1",
    "plano_zeus": "",
    "grupo_plano_zeus": "",
    "data_ativacao_zeus": "",
    "vencimento_zeus": "",
    "limite_creditos_zeus": "100",
    "tech_prefix_zeus": "",
    "bloquear_ligacoes_vc1_zeus": "S",
    "bloquear_ligacoes_cobrar_zeus": "S",
    "bloquear_ligacoes_ldn_zeus": "S",
    "bloquear_ligacoes_ldi_zeus": "S",
    "nao_perturbe_zeus": "1",
    "fullcontact": "",
    "ipaddr": "",
    "port": "",
    "regseconds": "",
    "useragent": "",
    "nat": "no",
    "host": "dynamic",
    "contactpermit": "",
    "contactdeny": "",
    "sippulse_dominio": "",
    "profile": "",
    "id_revenda_sip_pulse": "",
    "sippulse_rateplanid": "",
    "ddd": "",
    "ddi": "",
    "sippulse_city_code": "",
    "sippulse_local_area": "",
    "sippulse_lowCreditNotification": "true",
    "sippulse_activeIncomingCalls": "true",
    "sippulse_activeOutgoingCalls": "true",
    "sippulse_activatedailystatistics": "true",
    "sippulse_callsOnlyByIp": "true",
    "sippulse_daily_quota": "true",
    "sippulse_daily_quota_tipo": "M",
    "sippulse_dailyQuotaConsumed": "0",
    "sippulse_dailyQuotaLimit": "0",
    "plano_magnus": ""
   },
  json: true
  };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});

//Listar----------------------------
let request = require("request");
let token = '6:4dacdb8e47193e8cbbabe508c3c59b4547e463817b1d9b9a1d20ab4812fe1a62';
let options = { method: 'GET',
  url: 'https://HOST/webservice/v1/voip_sippeers',
  headers:
   {
     'Content-Type': 'application/json',
     Authorization: 'Basic ' + new Buffer.from(token).toString('base64'),
     ixcsoft: 'listar'
   },
  body:
   { qtype: 'voip_sippeers.id',
     query: '0',
     oper: '>',
     page: '1',
     rp: '20',
     sortname: 'voip_sippeers.id',
     sortorder: 'desc'
   },
  json: true
  };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});

                    